# Generated by Django 5.0 on 2023-12-17 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_1', models.CharField(max_length=255, verbose_name='Word 1')),
                ('word_2', models.CharField(max_length=255, verbose_name='Word 2')),
                ('definition_1', models.TextField(blank=True, null=True, verbose_name='Card 1 Definition')),
                ('definition_2', models.TextField(blank=True, null=True, verbose_name='Card 2 Definition')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/card_images/')),
            ],
            options={
                'verbose_name': 'Card',
                'verbose_name_plural': 'Cards',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_name', models.CharField(max_length=255, verbose_name='Language name')),
                ('language_api', models.CharField(blank=True, max_length=355, null=True)),
            ],
            options={
                'verbose_name': 'Language',
                'verbose_name_plural': 'Languages',
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Name')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Module description')),
                ('visibility', models.BooleanField(help_text='Click to hide your module from other users', verbose_name='Module visibility')),
                ('color', models.CharField(choices=[('r', 'red'), ('g', 'green'), ('b', 'blue'), ('g', 'gray')], default='g', max_length=255, verbose_name='Module color')),
            ],
            options={
                'verbose_name': 'Module',
                'verbose_name_plural': 'Modules',
            },
        ),
    ]
