# Generated by Django 5.0 on 2023-12-17 15:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Card', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='module',
            name='language_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_language_1', to='Card.language', verbose_name='Language 1'),
        ),
        migrations.AddField(
            model_name='module',
            name='language_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_language_2', to='Card.language', verbose_name='Language 2'),
        ),
        migrations.AddField(
            model_name='card',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Card.module', verbose_name='Card module'),
        ),
    ]
